-- AlterTable
ALTER TABLE "Day" ADD COLUMN     "totalAlcohol" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalOmega3" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalSteps" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Meal" ADD COLUMN     "alcohol" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "omega3" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "SavedMeal" ADD COLUMN     "alcohol" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "omega3" DOUBLE PRECISION NOT NULL DEFAULT 0;
